//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GestionAcademicaEntities : DbContext
    {
        public GestionAcademicaEntities()
            : base("name=GestionAcademicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administradores> Administradores { get; set; }
        public virtual DbSet<Aprendices> Aprendices { get; set; }
        public virtual DbSet<Asistencias> Asistencias { get; set; }
        public virtual DbSet<Competencias> Competencias { get; set; }
        public virtual DbSet<Fichas> Fichas { get; set; }
        public virtual DbSet<Instructores> Instructores { get; set; }
        public virtual DbSet<Programas> Programas { get; set; }
        public virtual DbSet<Reportes_Incapacidad> Reportes_Incapacidad { get; set; }
        public virtual DbSet<Soportes_Asistencia> Soportes_Asistencia { get; set; }
    
        public virtual ObjectResult<string> sp_IniciarSesion(string numero_documento, string tipo_documento, string contraseña)
        {
            var numero_documentoParameter = numero_documento != null ?
                new ObjectParameter("numero_documento", numero_documento) :
                new ObjectParameter("numero_documento", typeof(string));
    
            var tipo_documentoParameter = tipo_documento != null ?
                new ObjectParameter("tipo_documento", tipo_documento) :
                new ObjectParameter("tipo_documento", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_IniciarSesion", numero_documentoParameter, tipo_documentoParameter, contraseñaParameter);
        }
    
        public virtual int sp_OlvidarContraseña(string correoElectronico, string nuevaContraseña)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var nuevaContraseñaParameter = nuevaContraseña != null ?
                new ObjectParameter("NuevaContraseña", nuevaContraseña) :
                new ObjectParameter("NuevaContraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_OlvidarContraseña", correoElectronicoParameter, nuevaContraseñaParameter);
        }
    
        public virtual int sp_RegistrarUsuario(string nombre, string apellido, string correoElectronico, string contraseña, string tipoUsuario)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var tipoUsuarioParameter = tipoUsuario != null ?
                new ObjectParameter("TipoUsuario", tipoUsuario) :
                new ObjectParameter("TipoUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarUsuario", nombreParameter, apellidoParameter, correoElectronicoParameter, contraseñaParameter, tipoUsuarioParameter);
        }
    }
}
