//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reportes_Incapacidad
    {
        public int reporte_id { get; set; }
        public System.DateTime fecha_incapacidad { get; set; }
        public System.TimeSpan hora_incapacidad { get; set; }
        public int soporte_id { get; set; }
    
        public virtual Soportes_Asistencia Soportes_Asistencia { get; set; }
    }
}
