//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soportes_Asistencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soportes_Asistencia()
        {
            this.Reportes_Incapacidad = new HashSet<Reportes_Incapacidad>();
        }
    
        public int soporte_id { get; set; }
        public string tipo_incapacidad { get; set; }
        public string formato_soporte { get; set; }
        public int asistencia_id { get; set; }
    
        public virtual Asistencias Asistencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reportes_Incapacidad> Reportes_Incapacidad { get; set; }
    }
}
