//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codigos_Asistencia
    {
        public int codigo_id { get; set; }
        public string codigo { get; set; }
        public int ficha_id { get; set; }
        public System.DateTime fecha_generacion { get; set; }
        public System.TimeSpan hora_generacion { get; set; }
        public System.TimeSpan hora_expiracion { get; set; }
    
        public virtual Fichas Fichas { get; set; }
    }
}
