//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructores
    {
        public int instructor_id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string imagen { get; set; }
        public string correo_electronico { get; set; }
        public string contraseña { get; set; }
        public string numero_documento { get; set; }
        public string tipo_documento { get; set; }
        public string direccion { get; set; }
        public string numero { get; set; }
        public string tipo_instructor { get; set; }
        public int ficha_id { get; set; }
    
        public virtual Fichas Fichas { get; set; }
    }
}
